name: 'CI'

on:
  push:
    branches: [ master ]
  pull_request: ~
  schedule:
    - cron: "0 16 * * 1"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rubyversion: ['2.7', '3.0', '3.1']
    steps:
      - uses: actions/checkout@v3
      - name: set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.rubyversion }}
          rubygems: "3.0.0"
          bundler-cache: true
      - name: Install Dependencies
        run: make install
      - name: run tests
        run: make test
